name: actiontest1

on:
  push:
    branches:
      - main

jobs:
  Updatesite:
    runs-on: self-hosted
    env:
      Image_name: logeshK98/fincacalc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        id: vars
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          TAG=$(date +%Y%m%d)-$SHORT_SHA
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t docker.io/$Image_name:$TAG .
          docker images # Check if image is created successfully

      - name: Push Docker image to Docker Hub
        run: |
          docker push docker.io/$Image_name:$TAG

      - name: Deploy to server
        run: |
          # Pull the image
          docker pull docker.io/$Image_name:$TAG

          # Stop and remove existing container if it exists
          docker stop fincacalc || true
          docker rm fincacalc || true

          # Run the new container
          docker run -d --name fincacalc -p 7071:80 docker.io/$Image_name:$TAG
